--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-19-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MENU" 
   (	"MENUNAME" VARCHAR2(100 BYTE), 
	"UNITCOST" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.MENU
SET DEFINE OFF;
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴1',44000);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴2',27000);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴3',32000);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴4',8000);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴5',5500);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴6',18000);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴7',15000);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴8',8500);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴9',7500);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴10',30000);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴11',5500);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴12',18000);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴13',15000);
Insert into SCOTT.MENU (MENUNAME,UNITCOST) values ('메뉴14',8500);
--------------------------------------------------------
--  DDL for Index MENU_MENUNAME_UQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."MENU_MENUNAME_UQ" ON "SCOTT"."MENU" ("MENUNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger MENU_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."MENU_TRG" 
BEFORE INSERT ON MENU 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."MENU_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MENU" ADD CONSTRAINT "MENU_MENUNAME_UQ" UNIQUE ("MENUNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."MENU" MODIFY ("UNITCOST" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MENU" MODIFY ("MENUNAME" NOT NULL ENABLE);
