--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-19-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TABLEINFO
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TABLEINFO" 
   (	"SNO" NUMBER(4,0), 
	"TNO" NUMBER(4,0), 
	"SDATE" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ENTTIME" TIMESTAMP (6), 
	"STAYTIME" TIMESTAMP (6), 
	"PAYTIME" TIMESTAMP (6), 
	"PTOTAL" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.TABLEINFO
SET DEFINE OFF;
Insert into SCOTT.TABLEINFO (SNO,TNO,SDATE,ENTTIME,STAYTIME,PAYTIME,PTOTAL) values (4,2,' 2022-10-19 (수)',null,null,null,null);
Insert into SCOTT.TABLEINFO (SNO,TNO,SDATE,ENTTIME,STAYTIME,PAYTIME,PTOTAL) values (2,2,' 2022-10-19 (수)',null,null,null,null);
Insert into SCOTT.TABLEINFO (SNO,TNO,SDATE,ENTTIME,STAYTIME,PAYTIME,PTOTAL) values (3,2,' 2022-10-19 (수)',null,null,null,null);
Insert into SCOTT.TABLEINFO (SNO,TNO,SDATE,ENTTIME,STAYTIME,PAYTIME,PTOTAL) values (5,2,' 2022-10-19 (수)',null,null,null,null);
Insert into SCOTT.TABLEINFO (SNO,TNO,SDATE,ENTTIME,STAYTIME,PAYTIME,PTOTAL) values (6,2,' 2022-10-19 (수)',null,null,null,null);
Insert into SCOTT.TABLEINFO (SNO,TNO,SDATE,ENTTIME,STAYTIME,PAYTIME,PTOTAL) values (7,2,' 2022-10-19 (수)',null,null,null,null);
Insert into SCOTT.TABLEINFO (SNO,TNO,SDATE,ENTTIME,STAYTIME,PAYTIME,PTOTAL) values (8,2,' 2022-10-19 (수)',null,null,null,null);
Insert into SCOTT.TABLEINFO (SNO,TNO,SDATE,ENTTIME,STAYTIME,PAYTIME,PTOTAL) values (9,2,' 2022-10-19 (수)',null,null,null,null);
--------------------------------------------------------
--  DDL for Index TABLEINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."TABLEINFO_PK" ON "SCOTT"."TABLEINFO" ("SNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TABLEINFO_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."TABLEINFO_TRG1" 
BEFORE INSERT ON TABLEINFO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."TABLEINFO_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TABLEINFO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."TABLEINFO_TRG" 
BEFORE INSERT ON TABLEINFO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."TABLEINFO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TABLEINFO_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."TABLEINFO_TRG2" 
BEFORE INSERT ON TABLEINFO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SNO IS NULL THEN
      SELECT TABLEINFO_SEQ2.NEXTVAL INTO :NEW.SNO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCOTT"."TABLEINFO_TRG2" ENABLE;
--------------------------------------------------------
--  Constraints for Table TABLEINFO
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TABLEINFO" MODIFY ("SDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TABLEINFO" ADD CONSTRAINT "TABLEINFO_PK" PRIMARY KEY ("SNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."TABLEINFO" MODIFY ("TNO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TABLEINFO" MODIFY ("SNO" NOT NULL ENABLE);
